In [143]:
import pandas as pd
df = pd.read_csv("salary_data.csv")

In [144]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,Male,Bachelor's,Junior Developer,1,Small,Technology,Hyderabad,Yes,350000
1,25,Female,Master's,Data Analyst,2,Medium,Finance,Bangalore,No,520000
2,28,Male,Bachelor's,Software Engineer,4,Large,Technology,Mumbai,Yes,850000
3,30,Female,PhD,Data Scientist,5,Large,Research,Delhi,No,1200000
4,32,Male,Master's,Senior Developer,7,Large,Technology,Hyderabad,Yes,1400000

In [145]:
df.shape

(50, 10)

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               50 non-null     int64
 1   gender            50 non-null     object
 2   education_level   50 non-null     object
 3   job_title         50 non-null     object
 4   years_experience  50 non-null     int64
 5   company_size      50 non-null     object
 6   industry          50 non-null     object
 7   location          50 non-null     object
 8   remote_work       50 non-null     object
 9   salary            50 non-null     int64
dtypes: int64(3), object(7)
memory usage: 4.0+ KB

In [147]:
df.isnull().sum()

age                 0
gender              0
education_level     0
job_title           0
years_experience    0
company_size        0
industry            0
location            0
remote_work         0
salary              0
dtype: int64

In [148]:
df.dtypes

age                  int64
gender              object
education_level     object
job_title           object
years_experience     int64
company_size        object
industry            object
location            object
remote_work         object
salary               int64
dtype: object

In [149]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,Male,Bachelor's,Junior Developer,1,Small,Technology,Hyderabad,Yes,350000
1,25,Female,Master's,Data Analyst,2,Medium,Finance,Bangalore,No,520000
2,28,Male,Bachelor's,Software Engineer,4,Large,Technology,Mumbai,Yes,850000
3,30,Female,PhD,Data Scientist,5,Large,Research,Delhi,No,1200000
4,32,Male,Master's,Senior Developer,7,Large,Technology,Hyderabad,Yes,1400000

In [150]:
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [151]:
gender_map = { 
    'Male': 1,
    'Female':0 
}
df.gender = df.gender.map(gender_map)

In [152]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,1,Bachelor's,Junior Developer,1,Small,Technology,Hyderabad,Yes,350000
1,25,0,Master's,Data Analyst,2,Medium,Finance,Bangalore,No,520000
2,28,1,Bachelor's,Software Engineer,4,Large,Technology,Mumbai,Yes,850000
3,30,0,PhD,Data Scientist,5,Large,Research,Delhi,No,1200000
4,32,1,Master's,Senior Developer,7,Large,Technology,Hyderabad,Yes,1400000

In [153]:
df.education_level.unique()

array(["Bachelor's", "Master's", 'PhD', 'MBA'], dtype=object)

In [154]:
education_map = {
    "Bachelor's": 0, 
    "Master's":1, 
    'PhD':3, 
    'MBA':2
}
df.education_level = df.education_level.map(education_map)

In [155]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,1,0,Junior Developer,1,Small,Technology,Hyderabad,Yes,350000
1,25,0,1,Data Analyst,2,Medium,Finance,Bangalore,No,520000
2,28,1,0,Software Engineer,4,Large,Technology,Mumbai,Yes,850000
3,30,0,3,Data Scientist,5,Large,Research,Delhi,No,1200000
4,32,1,1,Senior Developer,7,Large,Technology,Hyderabad,Yes,1400000

In [156]:
df.job_title.nunique()

50

In [157]:
df.job_title.unique()

array(['Junior Developer', 'Data Analyst', 'Software Engineer',
       'Data Scientist', 'Senior Developer', 'Product Manager',
       'Business Analyst', 'ML Engineer', 'Research Scientist',
       'Engineering Manager', 'Frontend Developer', 'UX Designer',
       'DevOps Engineer', 'Cloud Architect', 'Senior Manager',
       'Junior Analyst', 'Principal Scientist', 'VP Engineering',
       'Full Stack Developer', 'AI Researcher', 'QA Engineer',
       'Data Engineer', 'Technical Lead', 'Content Strategist', 'CTO',
       'Android Developer', 'Product Analyst', 'Director of Sales',
       'HR Executive', 'Network Engineer', 'iOS Developer',
       'Systems Analyst', 'ML Research Lead', 'Support Engineer',
       'Scrum Master', 'Cybersecurity Analyst', 'BI Developer',
       'Operations Manager', 'UI Developer', 'Solutions Architect',
       'NLP Engineer', 'Database Administrator', 'Program Manager',
       'SEO Specialist', 'Head of Product', 'Quantitative Analyst',
       'Embedded Engineer', 'Research Director', 'Platform Engineer',
       'Intern Developer'], dtype=object)

In [158]:
from sklearn.preprocessing import LabelEncoder
job_title_le = LabelEncoder()
df.job_title = job_title_le.fit_transform(df.job_title)

In [159]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,1,0,22,1,Small,Technology,Hyderabad,Yes,350000
1,25,0,1,8,2,Medium,Finance,Bangalore,No,520000
2,28,1,0,41,4,Large,Technology,Mumbai,Yes,850000
3,30,0,3,10,5,Large,Research,Delhi,No,1200000
4,32,1,1,39,7,Large,Technology,Hyderabad,Yes,1400000

In [160]:
df.company_size.unique()

array(['Small', 'Medium', 'Large', 'Startup'], dtype=object)

In [161]:
company_size_map = {
    'Small':1, 
    'Medium':2, 
    'Large':3, 
    'Startup':0
}
df.company_size = df.company_size.map(company_size_map)

In [162]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,1,0,22,1,1,Technology,Hyderabad,Yes,350000
1,25,0,1,8,2,2,Finance,Bangalore,No,520000
2,28,1,0,41,4,3,Technology,Mumbai,Yes,850000
3,30,0,3,10,5,3,Research,Delhi,No,1200000
4,32,1,1,39,7,3,Technology,Hyderabad,Yes,1400000

In [163]:
df.industry.nunique()

15

In [164]:
df.industry.unique()

array(['Technology', 'Finance', 'Research', 'E-Commerce', 'Consulting',
       'Pharmaceuticals', 'Design', 'Banking', 'Marketing', 'HR',
       'Telecom', 'IT Services', 'Security', 'Logistics', 'Automotive'],
      dtype=object)

In [165]:
industry_le = LabelEncoder()
df.industry = industry_le.fit_transform(df.industry)

In [166]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,1,0,22,1,1,13,Hyderabad,Yes,350000
1,25,0,1,8,2,2,5,Bangalore,No,520000
2,28,1,0,41,4,3,13,Mumbai,Yes,850000
3,30,0,3,10,5,3,11,Delhi,No,1200000
4,32,1,1,39,7,3,13,Hyderabad,Yes,1400000

In [167]:
df.location.nunique()

6

In [168]:
df.location.unique()

array(['Hyderabad', 'Bangalore', 'Mumbai', 'Delhi', 'Pune', 'Chennai'],
      dtype=object)

In [169]:
location_le = LabelEncoder()
df.location = location_le.fit_transform(df.location)

In [170]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,1,0,22,1,1,13,3,Yes,350000
1,25,0,1,8,2,2,5,0,No,520000
2,28,1,0,41,4,3,13,4,Yes,850000
3,30,0,3,10,5,3,11,2,No,1200000
4,32,1,1,39,7,3,13,3,Yes,1400000

In [171]:
df.remote_work.unique()

array(['Yes', 'No'], dtype=object)

In [172]:
remote_work_map = {
    'Yes': 1, 'No':0
}
df.remote_work = df.remote_work.map(remote_work_map)

In [173]:
df.head()

,age,gender,education_level,job_title,years_experience,company_size,industry,location,remote_work,salary
0,22,1,0,22,1,1,13,3,1,350000
1,25,0,1,8,2,2,5,0,0,520000
2,28,1,0,41,4,3,13,4,1,850000
3,30,0,3,10,5,3,11,2,0,1200000
4,32,1,1,39,7,3,13,3,1,1400000

In [174]:
df.dtypes

age                 int64
gender              int64
education_level     int64
job_title           int32
years_experience    int64
company_size        int64
industry            int32
location            int32
remote_work         int64
salary              int64
dtype: object

In [175]:
x = df.drop('salary',axis=1)
y = df.salary

In [176]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.10)

In [177]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [178]:
y_pred = model.predict(x_test)
y_pred

array([ 857200., 1795000.,  362500., 1848500.,  362900.])

In [179]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [180]:
r2_score(y_test, y_pred)

0.9173101122870418

In [181]:
mean_squared_error(y_test, y_pred)

56379950000.0

In [182]:
mean_absolute_error(y_test, y_pred)

158940.0