In [1]:
import pandas as pd
df = pd.read_csv("movie_dataset.csv")
df

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [2]:
df.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [3]:
df.dropna(inplace=True)

In [4]:
df.isnull().sum()

id                   0
title                0
genre                0
original_language    0
overview             0
popularity           0
release_date         0
vote_average         0
vote_count           0
dtype: int64

In [5]:
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [6]:
df['movie_desc'] = df.overview + df.genre

In [7]:
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,movie_desc
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,In the continuing saga of the Corleone crime f...

In [8]:
df = df[['title', 'movie_desc']]

In [9]:
df

,title,movie_desc
0,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,Schindler's List,The true story of how businessman Oskar Schind...
4,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...
9995,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,Captain America,"During World War II, a brave, patriotic Americ..."
9998,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,Domino,Seeking justice for his partner’s murder by an...

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
vector = cv.fit_transform(df.movie_desc)

In [11]:
vector[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
df.title

0                            The Shawshank Redemption
1                         Dilwale Dulhania Le Jayenge
2                                       The Godfather
3                                    Schindler's List
4                              The Godfather: Part II
                            ...
9995                               The Last Airbender
9996                         Sharknado 3: Oh Hell No!
9997                                  Captain America
9998    In the Name of the King: A Dungeon Siege Tale
9999                                           Domino
Name: title, Length: 9985, dtype: object

In [13]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.41071429, 0.43355498, ..., 0.36126503, 0.44098105,
        0.33534681],
       [0.41071429, 1.        , 0.35768286, ..., 0.35245369, 0.29398737,
        0.24786503],
       [0.43355498, 0.35768286, 1.        , ..., 0.34229004, 0.37310927,
        0.2123977 ],
       ...,
       [0.36126503, 0.35245369, 0.34229004, ..., 1.        , 0.34287785,
        0.1870552 ],
       [0.44098105, 0.29398737, 0.37310927, ..., 0.34287785, 1.        ,
        0.24003968],
       [0.33534681, 0.24786503, 0.2123977 , ..., 0.1870552 , 0.24003968,
        1.        ]])

In [14]:
simi_df = pd.DataFrame(similarity, index=df.title, columns=df.title)

In [15]:
simi_df

title,The Shawshank Redemption,Dilwale Dulhania Le Jayenge,The Godfather,Schindler's List,The Godfather: Part II,Impossible Things,Spirited Away,Your Eyes Tell,Dou kyu sei – Classmates,Your Name.,...,The Last Exorcism Part II,Black Christmas,Prey,Hellraiser: Deader,Cell,The Last Airbender,Sharknado 3: Oh Hell No!,Captain America,In the Name of the King: A Dungeon Siege Tale,Domino
title,,,,,,,,,,,,,,,,,,,,,
The Shawshank Redemption,1.000000,0.410714,0.433555,0.287494,0.390199,0.225374,0.183117,0.318597,0.357284,0.228007,...,0.326219,0.214657,0.254588,0.322329,0.253898,0.402360,0.276026,0.361265,0.440981,0.335347
Dilwale Dulhania Le Jayenge,0.410714,1.000000,0.357683,0.175691,0.249294,0.281718,0.225374,0.327446,0.253860,0.120004,...,0.264082,0.239911,0.145479,0.312256,0.213809,0.285546,0.172516,0.352454,0.293987,0.247865
The Godfather,0.433555,0.357683,1.000000,0.252059,0.526316,0.136797,0.239395,0.247098,0.239691,0.116543,...,0.301726,0.107299,0.154529,0.195646,0.275776,0.346639,0.293198,0.342290,0.373109,0.212398
Schindler's List,0.287494,0.175691,0.252059,1.000000,0.271448,0.125988,0.125988,0.142481,0.201830,0.171736,...,0.222308,0.067763,0.162650,0.126131,0.167332,0.301836,0.216025,0.299482,0.262950,0.130410
The Godfather: Part II,0.390199,0.249294,0.526316,0.271448,1.000000,0.239395,0.273594,0.333045,0.285346,0.305926,...,0.282868,0.122628,0.220755,0.305697,0.291999,0.378152,0.314140,0.331593,0.291999,0.230098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
The Last Airbender,0.402360,0.285546,0.346639,0.301836,0.378152,0.225242,0.204765,0.231570,0.300694,0.209338,...,0.338729,0.128489,0.237915,0.146427,0.291386,1.000000,0.451413,0.409886,0.485643,0.211952
Sharknado 3: Oh Hell No!,0.276026,0.172516,0.293198,0.216025,0.314140,0.136083,0.136083,0.153897,0.218002,0.139122,...,0.330165,0.121988,0.210819,0.097312,0.335659,0.451413,1.000000,0.357528,0.387298,0.140859
Captain America,0.361265,0.352454,0.342290,0.299482,0.331593,0.139010,0.194613,0.331881,0.315478,0.177642,...,0.367927,0.149533,0.179461,0.188870,0.316503,0.409886,0.357528,1.000000,0.342878,0.187055
In the Name of the King: A Dungeon Siege Tale,0.440981,0.293987,0.373109,0.262950,0.291999,0.231900,0.147573,0.251661,0.253295,0.179605,...,0.302244,0.151186,0.163299,0.120605,0.260000,0.485643,0.387298,0.342878,1.000000,0.240040
Domino,0.335347,0.247865,0.212398,0.130410,0.230098,0.161015,0.069007,0.202326,0.245660,0.156772,...,0.202939,0.144338,0.148478,0.230283,0.152753,0.211952,0.140859,0.187055,0.240040,1.000000

In [16]:
def recommend(movie_name):
    score = simi_df[movie_name]
    result = score.sort_values(ascending=False).head(10)
    return list(result.index)

In [17]:
recommend('Iron Man')

['Iron Man',
 'Dead Rising: Watchtower',
 'District B13',
 'Turbo Kid',
 'Spawn',
 'Iron Man 3',
 "Zack Snyder's Justice League",
 'Terminator: Dark Fate',
 'Wonder Woman',
 'Predator']

In [19]:
recommend("Spider-Man")

['Spider-Man',
 'Spider-Man: Into the Spider-Verse',
 'Spider-Man: Homecoming',
 'The Amazing Spider-Man',
 'The Amazing Spider-Man 2',
 'Minnal Murali',
 'Spider-Man 3',
 'The Man with One Red Shoe',
 'Arachnophobia',
 'Spider-Man: No Way Home']

In [18]:
list(recommend('Predator').index)

TypeError: 'builtin_function_or_method' object is not iterable

In [ ]:
!pip install joblib

In [ ]:
import joblib
joblib.dump(simi_df, "similarity.joblib")

In [ ]:
list(simi_df.index)