In [29]:
import pandas as pd
df = pd.read_csv("sentiment_dataset.csv")
df

                                     text  label
0                       I love this movie      1
1                        This is terrible      0
2               Absolutely fantastic film      1
3                   Worst movie ever seen      0
4           Great performance by the cast      1
5              I hated every minute of it      0
6      Brilliant screenplay and direction      1
7         Boring and completely pointless      0
8       Highly recommend this masterpiece      1
9                Dull and lifeless acting      0
10       Amazing visual effects and story      1
11          Total waste of time and money      0
12      One of the best films I have seen      1
13       Disappointing and poorly written      0
14         Thoroughly enjoyed every scene      1
15           Terrible plot and bad acting      0
16         Wonderful cinematic experience      1
17              Not worth watching at all      0
18        Incredible story and great cast      1
19         Absolutely dreadful and boring      0
20         Loved the direction and acting      1
21            Very bad movie do not watch      0
22       Superb storytelling and emotions      1
23         Could not finish it was so bad      0
24         Fantastic from start to finish      1
25        Hated the script and everything      0
26       Exceptional film loved every bit      1
27  Very disappointing experience overall      0
28    Outstanding performances all around      1
29          Complete garbage not worth it      0
30     Really enjoyed this beautiful film      1
31        Awful movie terrible experience      0
32      Heartwarming and beautifully made      1
33               Dreadful waste of talent      0
34        Magnificent and truly inspiring      1
35     Boring predictable and poorly done      0
36       Stunning cinematography loved it      1
37      Worst experience in a cinema ever      0
38         Moved me to tears so beautiful      1
39        Nonsensical plot terrible movie      0
40      Gripping and emotionally powerful      1
41          Slow boring and uninteresting      0
42         Loved the characters and story      1
43        Dull uninspired and forgettable      0
44           A true cinematic masterpiece      1
45             Simply awful do not bother      0
46            Charming delightful and fun      1
47       Horribly written and acted badly      0
48       Perfect movie I enjoyed it fully      1
49           Painful to watch so very bad      0

In [30]:
df.shape

(50, 2)

In [31]:
df.head()

                            text  label
0              I love this movie      1
1               This is terrible      0
2      Absolutely fantastic film      1
3          Worst movie ever seen      0
4  Great performance by the cast      1

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    50 non-null     object
 1   label   50 non-null     int64
dtypes: int64(1), object(1)
memory usage: 928.0+ bytes

In [33]:
df.head()

                            text  label
0              I love this movie      1
1               This is terrible      0
2      Absolutely fantastic film      1
3          Worst movie ever seen      0
4  Great performance by the cast      1

In [34]:
df.label.value_counts()

label
1    25
0    25
Name: count, dtype: int64

In [35]:
df.text

0                         I love this movie
1                          This is terrible
2                 Absolutely fantastic film
3                     Worst movie ever seen
4             Great performance by the cast
5                I hated every minute of it
6        Brilliant screenplay and direction
7           Boring and completely pointless
8         Highly recommend this masterpiece
9                  Dull and lifeless acting
10         Amazing visual effects and story
11            Total waste of time and money
12        One of the best films I have seen
13         Disappointing and poorly written
14           Thoroughly enjoyed every scene
15             Terrible plot and bad acting
16           Wonderful cinematic experience
17                Not worth watching at all
18          Incredible story and great cast
19           Absolutely dreadful and boring
20           Loved the direction and acting
21              Very bad movie do not watch
22         Superb storytelling and emotions
23           Could not finish it was so bad
24           Fantastic from start to finish
25          Hated the script and everything
26         Exceptional film loved every bit
27    Very disappointing experience overall
28      Outstanding performances all around
29            Complete garbage not worth it
30       Really enjoyed this beautiful film
31          Awful movie terrible experience
32        Heartwarming and beautifully made
33                 Dreadful waste of talent
34          Magnificent and truly inspiring
35       Boring predictable and poorly done
36         Stunning cinematography loved it
37        Worst experience in a cinema ever
38           Moved me to tears so beautiful
39          Nonsensical plot terrible movie
40        Gripping and emotionally powerful
41            Slow boring and uninteresting
42           Loved the characters and story
43          Dull uninspired and forgettable
44             A true cinematic masterpiece
45               Simply awful do not bother
46              Charming delightful and fun
47         Horribly written and acted badly
48         Perfect movie I enjoyed it fully
49             Painful to watch so very bad
Name: text, dtype: object

In [36]:
texts = df.text.tolist()
labels = df.label.tolist()

In [37]:
texts

['I love this movie',
 'This is terrible',
 'Absolutely fantastic film',
 'Worst movie ever seen',
 'Great performance by the cast',
 'I hated every minute of it',
 'Brilliant screenplay and direction',
 'Boring and completely pointless',
 'Highly recommend this masterpiece',
 'Dull and lifeless acting',
 'Amazing visual effects and story',
 'Total waste of time and money',
 'One of the best films I have seen',
 'Disappointing and poorly written',
 'Thoroughly enjoyed every scene',
 'Terrible plot and bad acting',
 'Wonderful cinematic experience',
 'Not worth watching at all',
 'Incredible story and great cast',
 'Absolutely dreadful and boring',
 'Loved the direction and acting',
 'Very bad movie do not watch',
 'Superb storytelling and emotions',
 'Could not finish it was so bad',
 'Fantastic from start to finish',
 'Hated the script and everything',
 'Exceptional film loved every bit',
 'Very disappointing experience overall',
 'Outstanding performances all around',
 'Complete garbage not worth it',
 'Really enjoyed this beautiful film',
 'Awful movie terrible experience',
 'Heartwarming and beautifully made',
 'Dreadful waste of talent',
 'Magnificent and truly inspiring',
 'Boring predictable and poorly done',
 'Stunning cinematography loved it',
 'Worst experience in a cinema ever',
 'Moved me to tears so beautiful',
 'Nonsensical plot terrible movie',
 'Gripping and emotionally powerful',
 'Slow boring and uninteresting',
 'Loved the characters and story',
 'Dull uninspired and forgettable',
 'A true cinematic masterpiece',
 'Simply awful do not bother',
 'Charming delightful and fun',
 'Horribly written and acted badly',
 'Perfect movie I enjoyed it fully',
 'Painful to watch so very bad']

In [38]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=1000, oov_token='<OOV>')
tokenizer.fit_on_texts(texts)

seq = tokenizer.texts_to_sequences(texts)
seq

[[7, 49, 8, 3],
 [8, 50, 9],
 [23, 24, 15],
 [25, 3, 26, 27],
 [28, 51, 52, 4, 29],
 [7, 30, 16, 53, 10, 5],
 [54, 55, 2, 31],
 [11, 2, 56, 57],
 [58, 59, 8, 32],
 [33, 2, 60, 17],
 [61, 62, 63, 2, 18],
 [64, 34, 10, 65, 2, 66],
 [67, 10, 4, 68, 69, 7, 70, 27],
 [35, 2, 36, 37],
 [71, 19, 16, 72],
 [9, 38, 2, 12, 17],
 [73, 39, 13],
 [6, 40, 74, 75, 41],
 [76, 18, 2, 28, 29],
 [23, 42, 2, 11],
 [14, 4, 31, 2, 17],
 [20, 12, 3, 43, 6, 44],
 [77, 78, 2, 79],
 [80, 6, 45, 5, 81, 21, 12],
 [24, 82, 83, 22, 45],
 [30, 4, 84, 2, 85],
 [86, 15, 14, 16, 87],
 [20, 35, 13, 88],
 [89, 90, 41, 91],
 [92, 93, 6, 40, 5],
 [94, 19, 8, 46, 15],
 [47, 3, 9, 13],
 [95, 2, 96, 97],
 [42, 34, 10, 98],
 [99, 2, 100, 101],
 [11, 102, 2, 36, 103],
 [104, 105, 14, 5],
 [25, 13, 106, 48, 107, 26],
 [108, 109, 22, 110, 21, 46],
 [111, 38, 9, 3],
 [112, 2, 113, 114],
 [115, 11, 2, 116],
 [14, 4, 117, 2, 18],
 [33, 118, 2, 119],
 [48, 120, 39, 32],
 [121, 47, 43, 6, 122],
 [123, 124, 2, 125],
 [126, 37, 2, 127, 128],
 [129, 3, 7, 19, 5, 130],
 [131, 22, 44, 21, 20, 12]]

In [39]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

x = pad_sequences(seq, maxlen=10, padding='post')
y = np.array(labels)

In [40]:
texts[0], x[0]

('I love this movie', array([ 7, 49,  8,  3,  0,  0,  0,  0,  0,  0]))

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
model = Sequential([
    Embedding(input_dim=1000, output_dim=64, input_length=10),
    SpatialDropout1D(0.2),
    LSTM(64, dropout=0.2, recurrent_dropout=0.2),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

c:\Users\visha\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [42]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [43]:
model.fit(x, y, epochs=30)

Epoch 1/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.4600 - loss: 0.6948
Epoch 2/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4800 - loss: 0.6929
Epoch 3/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5400 - loss: 0.6927
Epoch 4/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6000 - loss: 0.6915
Epoch 5/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5600 - loss: 0.6909
Epoch 6/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7400 - loss: 0.6887
Epoch 7/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7600 - loss: 0.6872
Epoch 8/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7400 - loss: 0.6854
Epoch 9/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8200 - loss: 0.6818
Epoch 10/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9200 - loss: 0.6780
Epoch 11/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8600 - loss: 0.6723
Epoch 12/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9400 - loss: 0.6607
Epoch 13/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9800 - loss: 0.6469
Epoch 14/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9600 - loss: 0.6288
Epoch 15/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9600 - loss: 0.5918
Epoch 16/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9200 - loss: 0.5549
Epoch 17/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9600 - loss: 0.5004
Epoch 18/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4228
Epoch 19/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.3227
Epoch 20/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.2320
Epoch 21/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.1663
Epoch 22/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0838
Epoch 23/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.0456
Epoch 24/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.0205
Epoch 25/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.0103
Epoch 26/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0050
Epoch 27/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0030
Epoch 28/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 29/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.0014
Epoch 30/30
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 9.0968e-04

In [ ]:
new_text = ['I really enjoyed this movie']

seq = tokenizer.texts_to_sequences(new_text)
seq = pad_sequences(seq, maxlen=5)
seq

array([[ 7, 94, 19,  8,  3]])

In [57]:
pred = model.predict(seq)
if pred[0][0] > 0.5:
    print("Text is Positive")
else:
    print("Text is Negative")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
Text is Positive

In [63]:
text1 = ['the movie is  good']

seq = tokenizer.texts_to_sequences(text1)
seq = pad_sequences(seq)
seq

pred = model.predict(seq)
if pred[0][0] > 0.5:
    print("Text is Positive")
else:
    print("Text is Negative")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
Text is Positive