In [39]:
import pandas as pd

data = {
    "Name":["Rahul", "Alena", "Ravi", "Neha"],
    "Age" : [21,24,23,20],
    "City" : ['Delhi', 'Mumbai', 'Pune', 'Bangalore'],
    "Marks" :[90, 89, 70, 79]
}

df = pd.DataFrame(data)
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [40]:
df.head(2)

    Name  Age    City  Marks
0  Rahul   21   Delhi     90
1  Alena   24  Mumbai     89

In [41]:
df.head(3)

    Name  Age    City  Marks
0  Rahul   21   Delhi     90
1  Alena   24  Mumbai     89
2   Ravi   23    Pune     70

In [42]:
df.tail(1)

   Name  Age       City  Marks
3  Neha   20  Bangalore     79

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Marks   4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [44]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   22.000000  82.000000
std     1.825742   9.416298
min    20.000000  70.000000
25%    20.750000  76.750000
50%    22.000000  84.000000
75%    23.250000  89.250000
max    24.000000  90.000000

In [45]:
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [46]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [47]:
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [48]:
df.shape

(4, 4)

In [49]:
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [50]:
# df.Name
df['Name']

0    Rahul
1    Alena
2     Ravi
3     Neha
Name: Name, dtype: object

In [51]:
df.Age

0    21
1    24
2    23
3    20
Name: Age, dtype: int64

In [52]:
df.City

0        Delhi
1       Mumbai
2         Pune
3    Bangalore
Name: City, dtype: object

In [53]:
df[['Name', 'Marks']]

    Name  Marks
0  Rahul     90
1  Alena     89
2   Ravi     70
3   Neha     79

In [54]:
import pandas as pd
df = pd.read_csv("rapido_data.csv")
df

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN
9996,auto share,2024-07-10,2:47:20,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [55]:
df

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN
9996,auto share,2024-07-10,2:47:20,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [56]:
df.head(7)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm
5,bike lite,2024-07-07,20:01:20,cancelled,Indiranagar 7th Stage,Jayanagar,32,RD3945488262242659,48.96,NaN,NaN,NaN,NaN
6,bike lite,2024-07-01,22:54:20,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay

In [57]:
df.head(3)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay

In [58]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm

In [59]:
df.tail()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN
9996,auto share,2024-07-10,2:47:20,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [60]:
df.tail(10)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
9990,auto share,2024-07-18,1:30:20,completed,Koramangala 9th Block,Brigade Road Residency Road,67,RD3532347680366000,44.82,202.93,19.51,222.44,Paytm
9991,cab premium,2024-07-23,18:30:20,cancelled,Koramangala West,Yelahanka Old Town,94,RD4456688300060214,36.02,NaN,NaN,NaN,NaN
9992,auto share,2024-06-23,11:27:20,cancelled,Brigade Road Central,Ganganagar,94,RD2188000843207664,21.84,NaN,NaN,NaN,NaN
9993,cab economy,2024-07-17,14:25:20,completed,HSR Layout Sector 5 South,Nandi Hills,57,RD6855864651733693,37.36,239.09,1.36,240.45,QR scan
9994,cab premium,2024-07-17,7:52:20,cancelled,Jayanagar 2nd Block East,Brigade Road Residency Road,117,RD4300669776107381,11.44,NaN,NaN,NaN,NaN
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN
9996,auto share,2024-07-10,2:47:20,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [61]:
df.tail(3)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [62]:
df.sample(10)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
1277,auto,2024-07-15,3:52:20,cancelled,Peenya,Rajajinagar 6th Block,101,RD9261041734320968,3.19,NaN,NaN,NaN,NaN
7702,parcel,2024-07-05,19:44:20,cancelled,JP Nagar Phase 10,Victoria Layout,51,RD3825953320775118,1.39,NaN,NaN,NaN,NaN
9096,auto share,2024-07-14,19:21:20,completed,HSR Layout Sector 10 North,Kengeri,114,RD2419638133830494,10.86,442.17,30.28,472.45,GPay
7378,auto,2024-06-27,15:30:20,completed,Banashankari 3rd Stage,Jayanagar 9th Block East,31,RD1048102254100938,5.01,303.07,42.32,345.39,Paytm
2721,auto,2024-07-14,21:48:20,completed,Jayanagar 10th Block East,Malleshwaram 7th Block,24,RD8138602170221652,18.97,509.68,24.50,534.18,QR scan
6168,bike lite,2024-06-24,3:29:20,cancelled,HSR Layout Sector 7 South,Whitefield Borewell Road,116,RD7147899542777031,29.10,NaN,NaN,NaN,NaN
7280,bike,2024-07-04,0:13:20,cancelled,HSR Layout Sector 6 North,HSR Layout Sector 5 North,84,RD3721709526424970,6.22,NaN,NaN,NaN,NaN
5224,cab economy,2024-07-17,2:28:20,cancelled,RT Nagar,Bellandur,97,RD8791834474538684,22.02,NaN,NaN,NaN,NaN
5536,parcel,2024-07-06,21:16:20,completed,Richmond Town,Brigade Road South,99,RD9959757141377831,40.90,973.09,39.21,1012.30,GPay
8678,bike,2024-07-03,14:46:20,cancelled,Neelasandra,BTM Layout 2nd Stage,22,RD3307157316017170,45.07,NaN,NaN,NaN,NaN

In [63]:
df.sample(5)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
7714,bike,2024-07-19,19:36:20,completed,HSR Layout East,Banashankari 5th Stage,120,RD7570932404747697,46.81,328.00,19.39,347.39,phonePy
5361,bike,2024-07-11,15:02:20,completed,Indiranagar 9th Stage,Rajajinagar 5th Block,100,RD2321429254485161,13.41,251.98,26.54,278.52,Paytm
6517,bike lite,2024-07-23,3:27:20,cancelled,Banashankari 6th Stage,St. Marks Road,63,RD2217353852821126,28.03,NaN,NaN,NaN,NaN
7706,cab economy,2024-07-01,10:14:20,cancelled,Cooke Town,Jayanagar 10th Block East,24,RD6786866022817296,12.72,NaN,NaN,NaN,NaN
5211,bike,2024-07-07,5:37:20,cancelled,Kadubeesanahalli,Rajajinagar 4th Block,40,RD2116237001172330,36.02,NaN,NaN,NaN,NaN

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   services        10000 non-null  object
 1   date            10000 non-null  object
 2   time            10000 non-null  object
 3   ride_status     10000 non-null  object
 4   source          10000 non-null  object
 5   destination     10000 non-null  object
 6   duration        10000 non-null  int64
 7   ride_id         10000 non-null  object
 8   distance        10000 non-null  float64
 9   ride_charge     4611 non-null   float64
 10  misc_charge     4611 non-null   float64
 11  total_fare      4611 non-null   float64
 12  payment_method  4611 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 1015.8+ KB

In [65]:
df.columns

Index(['services', 'date', 'time', 'ride_status', 'source', 'destination',
       'duration', 'ride_id', 'distance', 'ride_charge', 'misc_charge',
       'total_fare', 'payment_method'],
      dtype='object')

In [66]:
df.shape

(10000, 13)

In [67]:
df.dtypes

services           object
date               object
time               object
ride_status        object
source             object
destination        object
duration            int64
ride_id            object
distance          float64
ride_charge       float64
misc_charge       float64
total_fare        float64
payment_method     object
dtype: object

In [68]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [69]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm

In [70]:
# df.services	
df['services']

0              bike
1         bike lite
2            parcel
3              bike
4       cab economy
           ...
9995           auto
9996     auto share
9997     auto share
9998    cab premium
9999    cab economy
Name: services, Length: 10000, dtype: object

In [71]:
df.source

0               Banashankari 7th Stage
1                    Indiranagar North
2          MG Road Mahatma Gandhi Road
3                             JP Nagar
4                     Whitefield North
                     ...
9995    Brigade Road Mota Royal Arcade
9996                       Frazer Town
9997        Brigade Road Church Street
9998             Rajajinagar 2nd Block
9999                      Hebbal North
Name: source, Length: 10000, dtype: object

In [72]:
df[['source', 'destination', 'total_fare']]

                              source                destination  total_fare
0             Banashankari 7th Stage              Richmond Road       95.41
1                  Indiranagar North              Sahakar Nagar      432.45
2        MG Road Mahatma Gandhi Road           Whitefield South      275.35
3                           JP Nagar      Rajajinagar 7th Block         NaN
4                   Whitefield North      Brigade Road Eva Mall      807.70
...                              ...                        ...         ...
9995  Brigade Road Mota Royal Arcade                Neelasandra         NaN
9996                     Frazer Town        MG Road Cubbon Park      147.96
9997      Brigade Road Church Street  HSR Layout Sector 5 North         NaN
9998           Rajajinagar 2nd Block         HSR Layout Central         NaN
9999                    Hebbal North       HSR Layout Sector 10      611.81

[10000 rows x 3 columns]

In [73]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm

In [74]:
df.iloc[3]

services                           bike
date                         2024-07-20
time                            5:38:20
ride_status                   cancelled
source                         JP Nagar
destination       Rajajinagar 7th Block
duration                             45
ride_id              RD7207154929912440
distance                          16.64
ride_charge                         NaN
misc_charge                         NaN
total_fare                          NaN
payment_method                      NaN
Name: 3, dtype: object

In [75]:
df.iloc[3000]

services                    cab economy
date                         2024-06-28
time                           19:18:20
ride_status                   cancelled
source                    JP Nagar West
destination       Indiranagar 2nd Stage
duration                             38
ride_id              RD9561801262501650
distance                          20.44
ride_charge                         NaN
misc_charge                         NaN
total_fare                          NaN
payment_method                      NaN
Name: 3000, dtype: object

In [76]:
df.loc[3000]

services                    cab economy
date                         2024-06-28
time                           19:18:20
ride_status                   cancelled
source                    JP Nagar West
destination       Indiranagar 2nd Stage
duration                             38
ride_id              RD9561801262501650
distance                          20.44
ride_charge                         NaN
misc_charge                         NaN
total_fare                          NaN
payment_method                      NaN
Name: 3000, dtype: object

In [77]:
import pandas as pd

# Create data
data = {
    "Name": ["Rahul", "Anita", "Vikram", "Sneha"],
    "City": ["Delhi", "Mumbai", "Chennai", "Hyderabad"],
    "Age": [25, 30, 28, 22]
}

# Create DataFrame with custom index
df1 = pd.DataFrame(data, index=[101, 102, 103, 104])

df1

       Name       City  Age
101   Rahul      Delhi   25
102   Anita     Mumbai   30
103  Vikram    Chennai   28
104   Sneha  Hyderabad   22

In [78]:
df1.loc[103]

Name     Vikram
City    Chennai
Age          28
Name: 103, dtype: object

In [79]:
df1.iloc[2]

Name     Vikram
City    Chennai
Age          28
Name: 103, dtype: object

In [81]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm

In [85]:
df[df.duration > 100]

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
10,auto,2024-07-07,20:38:20,completed,Jayanagar 6th Block East,HSR Layout Sector 5,113,RD7099134978086824,49.88,701.60,11.29,712.89,Cash
11,bike,2024-07-11,15:12:20,cancelled,Rajajinagar 3rd Block,Jayanagar 2nd Block East,106,RD5926553782821365,18.21,NaN,NaN,NaN,NaN
17,auto share,2024-07-22,10:59:20,cancelled,Jayanagar 10th Block East,Marathahalli Colony,115,RD7011984811787878,37.08,NaN,NaN,NaN,NaN
27,cab economy,2024-07-12,18:09:20,cancelled,Koramangala 2nd Block,Rajajinagar 3rd Block,109,RD7154821193229128,2.26,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,auto share,2024-07-17,6:01:20,cancelled,Malleshwaram 1st Block,Brigade Road,117,RD6037024647727904,37.19,NaN,NaN,NaN,NaN
9981,bike,2024-07-08,18:49:20,cancelled,Whitefield ECC Road,Jayanagar 7th Block,115,RD7267283462284149,49.64,NaN,NaN,NaN,NaN
9988,auto,2024-06-29,7:41:20,completed,Sarjapur Road,Kadubeesanahalli,105,RD8030683675488536,32.11,741.21,17.35,758.56,Amazon Pay
9994,cab premium,2024-07-17,7:52:20,cancelled,Jayanagar 2nd Block East,Brigade Road Residency Road,117,RD4300669776107381,11.44,NaN,NaN,NaN,NaN
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN

In [86]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm

In [89]:
df[df.services == "bike"]

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
11,bike,2024-07-11,15:12:20,cancelled,Rajajinagar 3rd Block,Jayanagar 2nd Block East,106,RD5926553782821365,18.21,NaN,NaN,NaN,NaN
13,bike,2024-06-29,22:31:20,cancelled,Whitefield Mahadevapura,Yelahanka New Town,12,RD8009610169324823,35.77,NaN,NaN,NaN,NaN
22,bike,2024-07-23,15:21:20,cancelled,Queens Road,Brigade Road Eva Mall,100,RD5232846266935209,42.87,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9972,bike,2024-07-12,10:50:20,completed,Ashok Nagar,BTM Layout 2nd Stage,75,RD4555404926914718,43.96,61.49,10.70,72.19,GPay
9975,bike,2024-07-11,19:58:20,completed,Brigade Road Mayo Hall,BTM Layout 1st Stage,55,RD2208153672860306,5.18,372.09,34.96,407.05,GPay
9981,bike,2024-07-08,18:49:20,cancelled,Whitefield ECC Road,Jayanagar 7th Block,115,RD7267283462284149,49.64,NaN,NaN,NaN,NaN
9984,bike,2024-07-18,1:50:20,cancelled,Brigade Road Residency Road,Jayanagar 2nd Block,85,RD6886620601331554,14.74,NaN,NaN,NaN,NaN
9985,bike,2024-06-27,21:34:20,completed,Kadubeesanahalli,Jayanagar 10th Block,22,RD7150131219186898,1.89,771.36,18.35,789.71,GPay

In [ ]:
c1 = df.total_fare > 400
c2 = df.payment_method == "Amazon Pay"
df[c1 & c2]

In [97]:
df[(df.total_fare > 400) & (df.payment_method == "Amazon Pay")]

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
6,bike lite,2024-07-01,22:54:20,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay
7,auto,2024-06-24,18:26:20,completed,Jayanagar 8th Block,Banashankari 6th Stage,28,RD8212250057688058,34.48,729.41,33.67,763.08,Amazon Pay
18,auto,2024-07-06,1:43:20,completed,Indiranagar North,HSR Layout Central,54,RD2034186068133556,32.65,723.76,13.58,737.34,Amazon Pay
28,cab premium,2024-07-12,2:43:20,completed,Vidyaranyapura,Malleshwaram 6th Block,47,RD2937871914336507,20.14,535.24,3.74,538.98,Amazon Pay
31,bike,2024-07-09,1:18:20,completed,Hebbal Dasarahalli,Malleshwaram 2nd Block,44,RD7796698949754419,30.19,405.89,21.11,427.00,Amazon Pay
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9883,auto share,2024-07-11,15:01:20,completed,Electronic City North,Nandini Layout,66,RD2949371319465284,19.88,982.44,15.93,998.37,Amazon Pay
9888,auto share,2024-07-10,1:23:20,completed,Rajajinagar,Shantinagar,14,RD2269258985700951,24.29,998.89,3.90,1002.79,Amazon Pay
9898,cab economy,2024-07-21,21:51:20,completed,Sadashivanagar,Rajajinagar 5th Block,10,RD1402309501949256,19.44,411.12,11.31,422.43,Amazon Pay
9914,parcel,2024-06-25,8:09:20,completed,Lavelle Road,HSR Layout East,91,RD1351661281516181,7.06,396.46,20.28,416.74,Amazon Pay
9988,auto,2024-06-29,7:41:20,completed,Sarjapur Road,Kadubeesanahalli,105,RD8030683675488536,32.11,741.21,17.35,758.56,Amazon Pay

In [103]:
df.sort_values(by="duration", ascending=False)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
8606,cab economy,2024-07-18,11:14:20,cancelled,HSR Layout Sector 3 South,Jayanagar 7th Block East,120,RD5576645395786031,35.22,NaN,NaN,NaN,NaN
9166,cab economy,2024-07-20,15:12:20,completed,Indiranagar 1st Stage,Hebbal North,120,RD4972045482404678,6.77,128.06,32.70,160.76,phonePy
5896,cab premium,2024-07-19,6:34:20,completed,Brigade Road Central,Hebbal Dasarahalli,120,RD2120327982129770,36.99,807.79,5.85,813.64,QR scan
2025,cab premium,2024-06-24,20:32:20,cancelled,Yeshwanthpur,Whitefield Immadihalli,120,RD9746741962382355,11.44,NaN,NaN,NaN,NaN
2621,cab premium,2024-06-23,23:53:20,completed,Brigade Road Bangalore Central,Kempapura,120,RD5354832167882469,46.47,62.48,13.94,76.42,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472,parcel,2024-07-04,14:11:20,cancelled,HSR Layout Sector 1 North,Hebbal South,5,RD4597052740110880,10.42,NaN,NaN,NaN,NaN
6244,bike,2024-07-01,21:15:20,cancelled,Koramangala 3rd Block,Banashankari 9th Stage,5,RD5734306493258659,35.94,NaN,NaN,NaN,NaN
1447,auto share,2024-06-26,14:45:20,completed,Jayanagar 8th Block East,MG Road Symphony Theatre,5,RD1757708442285746,31.52,724.09,16.87,740.96,Amazon Pay
7100,bike,2024-06-30,4:31:20,cancelled,Brigade Road Brigade Gateway,Brigade Road South,5,RD9956864550739039,24.87,NaN,NaN,NaN,NaN
1177,bike lite,2024-06-27,5:10:20,completed,Jayanagar 5th Block,Banashankari 7th Stage,5,RD9158520783352231,26.76,564.77,35.49,600.26,Paytm

In [100]:
df.sort_values(by="duration")

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
6244,bike,2024-07-01,21:15:20,cancelled,Koramangala 3rd Block,Banashankari 9th Stage,5,RD5734306493258659,35.94,NaN,NaN,NaN,NaN
7013,auto share,2024-06-28,23:15:20,completed,JP Nagar Phase 7,Banashankari 4th Stage,5,RD3794446120633913,35.27,63.81,36.86,100.67,Cash
703,parcel,2024-07-20,10:28:20,cancelled,MG Road South,Infantry Road,5,RD9920060818971296,30.13,NaN,NaN,NaN,NaN
8002,auto,2024-06-26,14:12:20,completed,Indiranagar 6th Stage,Ganganagar,5,RD8818489218884363,4.48,757.35,30.74,788.09,Amazon Pay
3378,auto,2024-07-11,15:53:20,completed,Basaveshwara Nagar,Rajajinagar 6th Block,5,RD6906717195965656,34.82,677.17,48.36,725.53,Amazon Pay
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8399,bike,2024-07-22,2:04:20,completed,Brigade Road Forum Mall,HSR Layout,120,RD6374988189324707,34.89,802.22,39.72,841.94,Amazon Pay
685,parcel,2024-07-19,10:49:20,completed,Nagarbhavi 2nd Stage,Marathahalli West,120,RD6690059335268951,18.29,228.76,31.82,260.58,Cash
4399,cab economy,2024-07-04,19:34:20,cancelled,HSR Layout Sector 2 North,Chikpet,120,RD7242226156401816,39.55,NaN,NaN,NaN,NaN
661,bike,2024-06-24,7:17:20,cancelled,Domlur,Jayanagar 3rd Block East,120,RD1195079022373809,32.98,NaN,NaN,NaN,NaN
8093,auto,2024-07-07,12:51:20,cancelled,MG Road Naga Theatre,Indiranagar Central,120,RD6217997604850782,38.58,NaN,NaN,NaN,NaN

In [104]:
df.shape

(10000, 13)

In [105]:
df['discount'] = 10

In [106]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,discount
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,10
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,10
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,10
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN,10
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,10

In [107]:
df['discount_amt'] = df.total_fare * 0.1

In [108]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,discount,discount_amt
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,10,9.541
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,10,43.245
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,10,27.535
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN,10,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,10,80.770

In [111]:
df.sample(10)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,discount,discount_amt
683,bike lite,2024-07-01,14:05:20,cancelled,JP Nagar 8th Phase,Jayanagar 7th Block East,52,RD9579663997602393,36.54,NaN,NaN,NaN,NaN,10,NaN
4335,bike,2024-07-19,12:41:20,completed,HSR Layout Sector 4,Indiranagar North,52,RD9722962699964010,11.31,764.95,24.03,788.98,Paytm,10,78.898
703,parcel,2024-07-20,10:28:20,cancelled,MG Road South,Infantry Road,5,RD9920060818971296,30.13,NaN,NaN,NaN,NaN,10,NaN
2734,parcel,2024-06-29,17:03:20,cancelled,Koramangala Central,JP Nagar 1st Phase,5,RD3412137458821956,4.19,NaN,NaN,NaN,NaN,10,NaN
1897,bike,2024-06-25,4:21:20,cancelled,Malleshwaram North,HSR Layout Sector 7 North,54,RD6538860008644443,29.72,NaN,NaN,NaN,NaN,10,NaN
3346,parcel,2024-07-07,0:49:20,completed,Jayanagar 2nd Block,Jayanagar 2nd Block,106,RD7993071246508614,15.33,959.75,0.59,960.34,Cash,10,96.034
7881,cab economy,2024-07-11,4:53:20,completed,JP Nagar Phase 3,Jayanagar 1st Block East,119,RD4846348498088097,43.69,641.50,19.06,660.56,GPay,10,66.056
8594,cab premium,2024-07-09,11:47:20,cancelled,Malleshwaram 10th Block,Avenue Road,11,RD4205907619577427,31.86,NaN,NaN,NaN,NaN,10,NaN
1332,bike,2024-06-24,1:16:20,completed,JP Nagar Phase 3,Koramangala 9th Block,16,RD2235213663070843,2.58,25.11,20.57,45.68,Cash,10,4.568
5437,auto,2024-06-24,8:10:20,cancelled,Jayanagar 10th Block,Electronic City West,93,RD4102721609720831,16.25,NaN,NaN,NaN,NaN,10,NaN

In [114]:
# df.isnull().sum()
df.isna().sum()

services             0
date                 0
time                 0
ride_status          0
source               0
destination          0
duration             0
ride_id              0
distance             0
ride_charge       5389
misc_charge       5389
total_fare        5389
payment_method    5389
discount             0
discount_amt      5389
dtype: int64

In [115]:
df.head(7)

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,discount,discount_amt
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,10,9.541
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,10,43.245
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,10,27.535
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN,10,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,10,80.770
5,bike lite,2024-07-07,20:01:20,cancelled,Indiranagar 7th Stage,Jayanagar,32,RD3945488262242659,48.96,NaN,NaN,NaN,NaN,10,NaN
6,bike lite,2024-07-01,22:54:20,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,10,69.200

In [116]:
df.total_fare.min()

18.81

In [117]:
df.total_fare.max()

1044.29

In [118]:
df.total_fare.mean()

530.5047408371286

In [119]:
df.total_fare.median()

528.9

In [120]:
df.total_fare.sum()

2446157.36

In [121]:
df.payment_method.mode()

0    QR scan
Name: payment_method, dtype: object

In [122]:
df.payment_method.unique()

array(['Amazon Pay', 'QR scan', 'GPay', nan, 'Paytm', 'Cash', 'phonePy'],
      dtype=object)

In [123]:
df.payment_method.value_counts()

payment_method
QR scan       797
Paytm         790
Amazon Pay    772
phonePy       760
Cash          755
GPay          737
Name: count, dtype: int64

In [124]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,discount,discount_amt
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,10,9.541
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,10,43.245
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,10,27.535
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN,10,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,10,80.770

In [125]:
df.services.value_counts()

services
auto           1479
auto share     1473
cab premium    1448
bike lite      1424
cab economy    1406
bike           1388
parcel         1382
Name: count, dtype: int64

In [126]:
df[['services','total_fare']]

         services  total_fare
0            bike       95.41
1       bike lite      432.45
2          parcel      275.35
3            bike         NaN
4     cab economy      807.70
...           ...         ...
9995         auto         NaN
9996   auto share      147.96
9997   auto share         NaN
9998  cab premium         NaN
9999  cab economy      611.81

[10000 rows x 2 columns]

In [127]:
df.groupby('services')['total_fare'].sum()

services
auto           391063.19
auto share     346887.26
bike           321782.00
bike lite      354782.15
cab economy    334850.51
cab premium    345342.95
parcel         351449.30
Name: total_fare, dtype: float64

In [129]:
import pandas as pd

data = {
    "City": ["Hyderabad", "Hyderabad", "Bangalore", "Bangalore", "Chennai", "Chennai"],
    "Product": ["Laptop", "Mobile", "Laptop", "Mobile", "Laptop", "Mobile"],
    "Sales": [50000, 20000, 45000, 25000, 40000, 15000],
    "Quantity": [5, 10, 4, 12, 3, 8]
}

df2 = pd.DataFrame(data)

df2

        City Product  Sales  Quantity
0  Hyderabad  Laptop  50000         5
1  Hyderabad  Mobile  20000        10
2  Bangalore  Laptop  45000         4
3  Bangalore  Mobile  25000        12
4    Chennai  Laptop  40000         3
5    Chennai  Mobile  15000         8

In [133]:
df2.groupby('City')['Sales'].sum()

City
Bangalore    70000
Chennai      55000
Hyderabad    70000
Name: Sales, dtype: int64

In [134]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,discount,discount_amt
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,10,9.541
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,10,43.245
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,10,27.535
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN,10,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,10,80.770