In [217]:
import pandas as pd

data = {
    "EmployeeID": [101,102,103,104,105],
    "Age": [25,32,29,41,36],
    "Gender": ["Male","Female","Male","Female","Male"],
    "Department": ["IT","HR","Finance","IT","Marketing"],
    "Salary": [50000,62000,58000,75000,540000,],
    "City": ["Delhi","Mumbai","Bangalore","Hyderabad","Chennai"],
    "Country": ["India","India","India","India","India"],
    "Experience": [2,6,4,10,7],
    "Education": ["Bachelors","Masters","Bachelors","PhD","Masters"],
}

df = pd.DataFrame(data)
df

,EmployeeID,Age,Gender,Department,Salary,City,Country,Experience,Education
0,101,25,Male,IT,50000,Delhi,India,2,Bachelors
1,102,32,Female,HR,62000,Mumbai,India,6,Masters
2,103,29,Male,Finance,58000,Bangalore,India,4,Bachelors
3,104,41,Female,IT,75000,Hyderabad,India,10,PhD
4,105,36,Male,Marketing,540000,Chennai,India,7,Masters

In [218]:
import pandas as pd
df = pd.read_csv("Big_Bazaar.csv")
df

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,NaN,2.0,1294.08,232.93,NaN,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,NaN,6.0,5804.46,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,NaN,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,GUW_44,Guwahati,Male,Frozen Foods,224.40,1.0,224.40,40.39,PhonePe,2.5,2024-12-15,23:26:24,Sunday
59996,MEE_24,Meerut,Female,Pet Supplies,824.22,6.0,4945.32,890.16,PhonePe,1.7,2025-04-21,07:40:02,Monday
59997,NaN,Faridabad,Female,Dairy Products,759.40,7.0,5315.80,956.84,NaN,4.2,2024-02-12,13:34:01,Monday
59998,ALL_34,Allahabad,Female,Fruits & Vegetables,370.77,8.0,2966.16,533.91,Mobikwik,3.2,2024-09-10,16:57:06,Tuesday
59999,CHA_45,Chandigarh,Female,Fruits & Vegetables,134.36,2.0,268.72,48.37,Debit Card,2.0,2024-10-13,08:44:45,Sunday

In [219]:
df.shape

(60000, 13)

In [220]:
df.isnull().sum()

branch_code         3120
city                2989
gender              3011
product_category    2997
unit_price          2993
quantity            3007
total_price         2992
gst                 3019
payment_method      2999
rating              3000
date                2993
time                2991
day                 2994
dtype: int64

In [221]:
df.to_csv("Big_Bazaar.csv", index=False)

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   branch_code       56880 non-null  object
 1   city              57011 non-null  object
 2   gender            56989 non-null  object
 3   product_category  57003 non-null  object
 4   unit_price        57007 non-null  float64
 5   quantity          56993 non-null  float64
 6   total_price       57008 non-null  float64
 7   gst               56981 non-null  float64
 8   payment_method    57001 non-null  object
 9   rating            57000 non-null  float64
 10  date              57007 non-null  object
 11  time              57009 non-null  object
 12  day               57006 non-null  object
dtypes: float64(5), object(8)
memory usage: 6.0+ MB

In [223]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,NaN,2.0,1294.08,232.93,NaN,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,NaN,6.0,5804.46,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,NaN,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [224]:
df.isnull().sum()

branch_code         3120
city                2989
gender              3011
product_category    2997
unit_price          2993
quantity            3007
total_price         2992
gst                 3019
payment_method      2999
rating              3000
date                2993
time                2991
day                 2994
dtype: int64

In [225]:
# df.dropna(inplace=True)

In [226]:
# df.isnull().sum()

In [227]:
df.shape

(60000, 13)

In [228]:
df.fillna(0)

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,0.00,2.0,1294.08,232.93,0,2.6,2024-07-16,15:46:42,0
1,GUW_44,Guwahati,Male,Frozen Foods,0.00,6.0,5804.46,0.00,Mobikwik,2.2,2024-06-15,0,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,0.0,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,GUW_44,Guwahati,Male,Frozen Foods,224.40,1.0,224.40,40.39,PhonePe,2.5,2024-12-15,23:26:24,Sunday
59996,MEE_24,Meerut,Female,Pet Supplies,824.22,6.0,4945.32,890.16,PhonePe,1.7,2025-04-21,07:40:02,Monday
59997,0,Faridabad,Female,Dairy Products,759.40,7.0,5315.80,956.84,0,4.2,2024-02-12,13:34:01,Monday
59998,ALL_34,Allahabad,Female,Fruits & Vegetables,370.77,8.0,2966.16,533.91,Mobikwik,3.2,2024-09-10,16:57:06,Tuesday
59999,CHA_45,Chandigarh,Female,Fruits & Vegetables,134.36,2.0,268.72,48.37,Debit Card,2.0,2024-10-13,08:44:45,Sunday

In [229]:
df.branch_code.isnull().sum()

3120

In [230]:
df.branch_code.nunique()

48

In [231]:
df.branch_code.value_counts()

branch_code
SRI_29    1286
SOL_46    1251
HOW_36    1248
AMR_32    1242
NAS_22    1239
VAS_27    1231
LUD_20    1216
DEL_00    1215
HYD_05    1213
RAI_43    1212
KAL_26    1206
VIS_16    1204
IND_13    1204
JAI_08    1200
ALL_34    1200
MEE_24    1198
GWA_39    1197
PAT_17    1195
GHA_19    1193
AGR_21    1191
THA_14    1185
NAV_33    1185
VAD_18    1184
JOD_41    1184
CHE_03    1183
BAN_04    1182
SUR_09    1181
GUW_44    1181
FAR_23    1179
NAG_12    1178
AUR_30    1178
RAJ_25    1175
KAN_11    1174
RAN_35    1174
BHO_15    1173
MAD_42    1166
AHM_06    1164
NOI_40    1164
HUB_47    1157
DHA_31    1154
CHA_45    1148
JAB_38    1148
LUC_10    1143
KOL_02    1131
VAR_28    1121
COI_37    1121
MUM_01    1116
PUN_07    1110
Name: count, dtype: int64

In [232]:
val = df.branch_code.mode()
val[0]

'SRI_29'

In [233]:
df.branch_code.fillna(val[0], inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_24144\4043337536.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.branch_code.fillna(val[0], inplace=True)

In [234]:
df.branch_code.isnull().sum()

0

In [235]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,NaN,2.0,1294.08,232.93,NaN,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,NaN,6.0,5804.46,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,NaN,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [236]:
df.city.isnull().sum()

2989

In [237]:
val = df.city.mode()
val[0]

'Srinagar'

In [238]:
df.city.fillna(val[0], inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_24144\3818017380.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.city.fillna(val[0], inplace=True)

In [239]:
df.city.isnull().sum()

0

In [240]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,NaN,2.0,1294.08,232.93,NaN,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,NaN,6.0,5804.46,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,NaN,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [241]:
df.gender.isnull().sum()

3011

In [242]:
val = df.gender.mode()
val[0]

'Female'

In [243]:
df.gender.fillna(val[0], inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_24144\1818949269.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.gender.fillna(val[0], inplace=True)

In [244]:
df.gender.isnull().sum()

0

In [245]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,NaN,2.0,1294.08,232.93,NaN,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,NaN,6.0,5804.46,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,NaN,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [246]:
df.unit_price.isnull().sum()

2993

In [247]:
val = df.unit_price.mean()
val = round(val, 2)
val

677.74

In [248]:
df.unit_price.fillna(val, inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_24144\1877510489.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.unit_price.fillna(val, inplace=True)

In [249]:
df.unit_price.isnull().sum()

0

In [250]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,677.74,2.0,1294.08,232.93,NaN,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,677.74,6.0,5804.46,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,NaN,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [251]:
df.quantity.isnull().sum()

3007

In [252]:
val = df.quantity.median()
val

6.0

In [253]:
# df.quantity.fillna(val, inplace=True)
df.quantity = df.quantity.fillna(val)

In [254]:
df.quantity.isnull().sum()

0

In [255]:
df.isnull().sum()

branch_code            0
city                   0
gender                 0
product_category    2997
unit_price             0
quantity               0
total_price         2992
gst                 3019
payment_method      2999
rating              3000
date                2993
time                2991
day                 2994
dtype: int64

In [256]:
df.product_category.isnull().sum()

2997

In [257]:
df.product_category.fillna(method="ffill", inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_24144\1060332187.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.product_category.fillna(method="ffill", inplace=True)
C:\Users\visha\AppData\Local\Temp\ipykernel_24144\1060332187.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.product_category.fillna(method="ffill", inplace=True)

In [258]:
df.product_category.isnull().sum()

0

In [259]:
df.isnull().sum()

branch_code            0
city                   0
gender                 0
product_category       0
unit_price             0
quantity               0
total_price         2992
gst                 3019
payment_method      2999
rating              3000
date                2993
time                2991
day                 2994
dtype: int64

In [260]:
df.payment_method.fillna(method="bfill", inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_24144\517301043.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.payment_method.fillna(method="bfill", inplace=True)
C:\Users\visha\AppData\Local\Temp\ipykernel_24144\517301043.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.payment_method.fillna(method="bfill", inplace=True)

In [261]:
df.payment_method.isnull().sum()

0

In [262]:
df.isnull().sum()

branch_code            0
city                   0
gender                 0
product_category       0
unit_price             0
quantity               0
total_price         2992
gst                 3019
payment_method         0
rating              3000
date                2993
time                2991
day                 2994
dtype: int64

In [263]:
df.rating.isnull().sum()

3000

In [264]:
# df.rating.interpolate(inplace=True)

In [265]:
df.rating.isnull().sum()

3000

In [266]:
df.isnull().sum()

branch_code            0
city                   0
gender                 0
product_category       0
unit_price             0
quantity               0
total_price         2992
gst                 3019
payment_method         0
rating              3000
date                2993
time                2991
day                 2994
dtype: int64

In [267]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,677.74,2.0,1294.08,232.93,Mobikwik,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,677.74,6.0,5804.46,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,6.0,266.31,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [268]:
df.total_price = df.unit_price * df.quantity

In [269]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,677.74,2.0,1355.48,232.93,Mobikwik,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,677.74,6.0,4066.44,NaN,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,6.0,532.62,47.94,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,41.80,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,540.99,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [270]:
df.gst.isnull().sum()

3019

In [271]:
df.gst = df.total_price * 0.05

In [272]:
df.gst.isnull().sum()

0

In [273]:
df.isnull().sum()

branch_code            0
city                   0
gender                 0
product_category       0
unit_price             0
quantity               0
total_price            0
gst                    0
payment_method         0
rating              3000
date                2993
time                2991
day                 2994
dtype: int64

In [274]:
df.date

0        2024-07-16
1        2024-06-15
2        2024-12-14
3        2025-03-16
4        2024-08-04
            ...
59995    2024-12-15
59996    2025-04-21
59997    2024-02-12
59998    2024-09-10
59999    2024-10-13
Name: date, Length: 60000, dtype: object

In [275]:
df.rating.isnull().sum()

3000

In [276]:
from sklearn.impute import KNNImputer
im = KNNImputer(n_neighbors=3)
# df.rating = im.fit_transform(df[['rating']])

In [277]:
df.rating.isnull().sum()

3000

In [278]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

im = IterativeImputer()
df.rating = im.fit_transform(df[['rating']])

In [279]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
0,FAR_23,Faridabad,Female,Home Decor,677.74,2.0,1355.48,67.774,Mobikwik,2.6,2024-07-16,15:46:42,NaN
1,GUW_44,Guwahati,Male,Frozen Foods,677.74,6.0,4066.44,203.322,Mobikwik,2.2,2024-06-15,NaN,Saturday
2,PAT_17,Patna,Female,Bakery,88.77,6.0,532.62,26.631,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,11.610,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,150.276,Debit Card,3.0,2024-08-04,03:57:11,Sunday

In [280]:
df.isna().sum()

branch_code            0
city                   0
gender                 0
product_category       0
unit_price             0
quantity               0
total_price            0
gst                    0
payment_method         0
rating                 0
date                2993
time                2991
day                 2994
dtype: int64

In [281]:
df.dropna(inplace=True)

In [282]:
df.shape

(51458, 13)

In [283]:
df.isna().sum()

branch_code         0
city                0
gender              0
product_category    0
unit_price          0
quantity            0
total_price         0
gst                 0
payment_method      0
rating              0
date                0
time                0
day                 0
dtype: int64

In [284]:
df[df.duplicated()]

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
1708,FAR_23,Faridabad,Male,Frozen Foods,690.73,2.0,1381.46,69.0730,Amazon Pay,3.5,2024-11-26,06:56:13,Tuesday
1986,NAS_22,Nashik,Female,Sports Equipment,250.36,6.0,1502.16,75.1080,Paytm,1.7,2025-01-20,12:10:53,Monday
2238,VIS_16,Visakhapatnam,Male,Beverages,368.17,1.0,368.17,18.4085,Google Pay,4.2,2025-06-19,06:26:05,Thursday
4059,MAD_42,Madurai,Male,Home Decor,787.93,2.0,1575.86,78.7930,Mobikwik,4.8,2024-02-06,00:21:10,Tuesday
4776,THA_14,Thane,Male,Health & Wellness,533.38,1.0,533.38,26.6690,Google Pay,2.3,2023-09-05,07:10:59,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59843,NOI_40,Noida,Male,Personal Care,55.15,8.0,441.20,22.0600,Cash,1.6,2024-01-14,05:16:04,Sunday
59863,AMR_32,Amritsar,Male,Personal Care,691.71,2.0,1383.42,69.1710,Cash,3.9,2024-04-19,13:23:47,Friday
59916,LUC_10,Lucknow,Male,Health & Wellness,629.72,9.0,5667.48,283.3740,PhonePe,1.8,2024-05-05,22:44:36,Sunday
59948,VIS_16,Visakhapatnam,Female,Stationery,256.25,9.0,2306.25,115.3125,Google Pay,1.2,2024-04-04,01:24:56,Thursday
59965,RAJ_25,Rajkot,Female,Sports Equipment,219.28,1.0,219.28,10.9640,Mobikwik,1.9,2024-01-16,20:43:53,Tuesday

In [285]:
df.duplicated().sum()

694

In [286]:
df.drop_duplicates(inplace=True)

In [287]:
df.duplicated().sum()

0

In [288]:
df.dtypes

branch_code          object
city                 object
gender               object
product_category     object
unit_price          float64
quantity            float64
total_price         float64
gst                 float64
payment_method       object
rating              float64
date                 object
time                 object
day                  object
dtype: object

In [293]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day
2,PAT_17,Patna,Female,Bakery,88.77,6.0,532.62,26.631,Cash,3.8,2024-12-14,14:27:15,Saturday
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,11.610,PhonePe,1.3,2025-03-16,22:10:38,Sunday
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,150.276,Debit Card,3.0,2024-08-04,03:57:11,Sunday
5,SRI_29,Srinagar,Female,Frozen Foods,42.30,2.0,84.60,4.230,Google Pay,1.4,2024-07-11,06:58:35,Thursday
6,SOL_46,Srinagar,Male,Personal Care,463.13,4.0,1852.52,92.626,Debit Card,1.3,2025-06-17,14:42:34,Tuesday

In [294]:
temp = df.date + " " + df.time
df['datetime'] = pd.to_datetime(temp)

In [295]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,date,time,day,datetime
2,PAT_17,Patna,Female,Bakery,88.77,6.0,532.62,26.631,Cash,3.8,2024-12-14,14:27:15,Saturday,2024-12-14 14:27:15
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,11.610,PhonePe,1.3,2025-03-16,22:10:38,Sunday,2025-03-16 22:10:38
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,150.276,Debit Card,3.0,2024-08-04,03:57:11,Sunday,2024-08-04 03:57:11
5,SRI_29,Srinagar,Female,Frozen Foods,42.30,2.0,84.60,4.230,Google Pay,1.4,2024-07-11,06:58:35,Thursday,2024-07-11 06:58:35
6,SOL_46,Srinagar,Male,Personal Care,463.13,4.0,1852.52,92.626,Debit Card,1.3,2025-06-17,14:42:34,Tuesday,2025-06-17 14:42:34

In [296]:
df.drop(['date','time'], axis=1, inplace=True)

In [297]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,day,datetime
2,PAT_17,Patna,Female,Bakery,88.77,6.0,532.62,26.631,Cash,3.8,Saturday,2024-12-14 14:27:15
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,11.610,PhonePe,1.3,Sunday,2025-03-16 22:10:38
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,150.276,Debit Card,3.0,Sunday,2024-08-04 03:57:11
5,SRI_29,Srinagar,Female,Frozen Foods,42.30,2.0,84.60,4.230,Google Pay,1.4,Thursday,2024-07-11 06:58:35
6,SOL_46,Srinagar,Male,Personal Care,463.13,4.0,1852.52,92.626,Debit Card,1.3,Tuesday,2025-06-17 14:42:34

In [298]:
df.dtypes

branch_code                 object
city                        object
gender                      object
product_category            object
unit_price                 float64
quantity                   float64
total_price                float64
gst                        float64
payment_method              object
rating                     float64
day                         object
datetime            datetime64[ns]
dtype: object

In [299]:
df.head()

,branch_code,city,gender,product_category,unit_price,quantity,total_price,gst,payment_method,rating,day,datetime
2,PAT_17,Patna,Female,Bakery,88.77,6.0,532.62,26.631,Cash,3.8,Saturday,2024-12-14 14:27:15
3,MEE_24,Meerut,Male,Snacks,77.40,3.0,232.20,11.610,PhonePe,1.3,Sunday,2025-03-16 22:10:38
4,THA_14,Thane,Male,Pet Supplies,751.38,4.0,3005.52,150.276,Debit Card,3.0,Sunday,2024-08-04 03:57:11
5,SRI_29,Srinagar,Female,Frozen Foods,42.30,2.0,84.60,4.230,Google Pay,1.4,Thursday,2024-07-11 06:58:35
6,SOL_46,Srinagar,Male,Personal Care,463.13,4.0,1852.52,92.626,Debit Card,1.3,Tuesday,2025-06-17 14:42:34