In [1]:
import pandas as pd
df = pd.read_csv("rapido_data.csv")
df

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN
9996,auto share,2024-07-10,2:47:20,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [2]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm

In [3]:
df.tail()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN
9996,auto share,2024-07-10,2:47:20,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   services        10000 non-null  object
 1   date            10000 non-null  object
 2   time            10000 non-null  object
 3   ride_status     10000 non-null  object
 4   source          10000 non-null  object
 5   destination     10000 non-null  object
 6   duration        10000 non-null  int64
 7   ride_id         10000 non-null  object
 8   distance        10000 non-null  float64
 9   ride_charge     4611 non-null   float64
 10  misc_charge     4611 non-null   float64
 11  total_fare      4611 non-null   float64
 12  payment_method  4611 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 1015.8+ KB

In [5]:
df

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,auto,2024-07-01,9:57:20,cancelled,Brigade Road Mota Royal Arcade,Neelasandra,120,RD8489738606219832,10.70,NaN,NaN,NaN,NaN
9996,auto share,2024-07-10,2:47:20,completed,Frazer Town,MG Road Cubbon Park,71,RD9340718348411258,13.27,124.72,23.24,147.96,phonePy
9997,auto share,2024-07-06,23:56:20,cancelled,Brigade Road Church Street,HSR Layout Sector 5 North,71,RD9632805396891647,2.41,NaN,NaN,NaN,NaN
9998,cab premium,2024-07-23,6:10:20,cancelled,Rajajinagar 2nd Block,HSR Layout Central,26,RD1640451808051338,45.75,NaN,NaN,NaN,NaN
9999,cab economy,2024-07-20,7:42:20,completed,Hebbal North,HSR Layout Sector 10,88,RD3004823158884110,19.86,565.39,46.42,611.81,Paytm

In [6]:
df.services

0              bike
1         bike lite
2            parcel
3              bike
4       cab economy
           ...
9995           auto
9996     auto share
9997     auto share
9998    cab premium
9999    cab economy
Name: services, Length: 10000, dtype: object

In [7]:
df.duration

0        99
1        48
2       112
3        45
4        44
       ...
9995    120
9996     71
9997     71
9998     26
9999     88
Name: duration, Length: 10000, dtype: int64

In [8]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
3,bike,2024-07-20,5:38:20,cancelled,JP Nagar,Rajajinagar 7th Block,45,RD7207154929912440,16.64,NaN,NaN,NaN,NaN
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm

In [9]:
df.isnull().sum()

services             0
date                 0
time                 0
ride_status          0
source               0
destination          0
duration             0
ride_id              0
distance             0
ride_charge       5389
misc_charge       5389
total_fare        5389
payment_method    5389
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

services          0
date              0
time              0
ride_status       0
source            0
destination       0
duration          0
ride_id           0
distance          0
ride_charge       0
misc_charge       0
total_fare        0
payment_method    0
dtype: int64

In [13]:
df.duplicated().sum()

0

In [14]:
df.dtypes

services           object
date               object
time               object
ride_status        object
source             object
destination        object
duration            int64
ride_id            object
distance          float64
ride_charge       float64
misc_charge       float64
total_fare        float64
payment_method     object
dtype: object

In [22]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm
6,bike lite,2024-07-01,22:54:20,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay

In [23]:
temp = df.date + " " + df.time
df['datetime'] = pd.to_datetime(temp)

In [24]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,2024-06-23,19:18:20,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,2024-07-06,2:42:20,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,2024-07-19,17:55:20,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
4,cab economy,2024-07-12,19:36:20,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20
6,bike lite,2024-07-01,22:54:20,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20

In [25]:
df.drop(['date', 'time'], axis=1, inplace=True)

In [26]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20

In [27]:
df.datetime

0      2024-06-23 19:18:20
1      2024-07-06 02:42:20
2      2024-07-19 17:55:20
4      2024-07-12 19:36:20
6      2024-07-01 22:54:20
               ...
9988   2024-06-29 07:41:20
9990   2024-07-18 01:30:20
9993   2024-07-17 14:25:20
9996   2024-07-10 02:47:20
9999   2024-07-20 07:42:20
Name: datetime, Length: 4611, dtype: datetime64[ns]

In [30]:
df.datetime.dt.year

0       2024
1       2024
2       2024
4       2024
6       2024
        ...
9988    2024
9990    2024
9993    2024
9996    2024
9999    2024
Name: datetime, Length: 4611, dtype: int32

In [31]:
df.datetime.dt.day

0       23
1        6
2       19
4       12
6        1
        ..
9988    29
9990    18
9993    17
9996    10
9999    20
Name: datetime, Length: 4611, dtype: int32

In [32]:
df.datetime.dt.hour

0       19
1        2
2       17
4       19
6       22
        ..
9988     7
9990     1
9993    14
9996     2
9999     7
Name: datetime, Length: 4611, dtype: int32

In [34]:
df['day_name'] = df.datetime.dt.day_name()

In [35]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday

In [37]:
df['year'] = df.datetime.dt.year

In [38]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024

In [40]:
df.datetime

0      2024-06-23 19:18:20
1      2024-07-06 02:42:20
2      2024-07-19 17:55:20
4      2024-07-12 19:36:20
6      2024-07-01 22:54:20
               ...
9988   2024-06-29 07:41:20
9990   2024-07-18 01:30:20
9993   2024-07-17 14:25:20
9996   2024-07-10 02:47:20
9999   2024-07-20 07:42:20
Name: datetime, Length: 4611, dtype: datetime64[ns]

In [41]:
df['hour'] = df.datetime.dt.hour

In [42]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024,19
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024,2
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024,19
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024,22

In [43]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024,19
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024,2
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024,19
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024,22

In [44]:
df.services.unique()

array(['bike', 'bike lite', 'parcel', 'cab economy', 'auto', 'auto share',
       'cab premium'], dtype=object)

In [45]:
df.shape

(4611, 15)

In [46]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024,19
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024,2
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024,19
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024,22

In [48]:
df.services.value_counts()

services
auto           718
auto share     690
cab premium    657
cab economy    650
bike lite      644
parcel         635
bike           617
Name: count, dtype: int64

In [51]:
df.datetime.dt.date.value_counts()

datetime
2024-07-07    176
2024-06-30    168
2024-06-29    164
2024-06-24    162
2024-07-06    160
2024-06-27    159
2024-07-02    158
2024-07-21    158
2024-07-19    154
2024-07-23    153
2024-07-04    152
2024-06-26    151
2024-06-25    150
2024-07-15    150
2024-07-01    149
2024-07-03    149
2024-07-13    147
2024-07-05    147
2024-06-28    147
2024-07-11    145
2024-07-08    142
2024-06-23    141
2024-07-09    141
2024-07-14    139
2024-07-20    137
2024-07-10    137
2024-07-22    137
2024-07-17    136
2024-07-16    134
2024-07-18    134
2024-07-12    134
Name: count, dtype: int64

In [54]:
df.datetime.dt.hour.value_counts()

datetime
8     230
17    216
23    210
18    208
15    205
20    203
5     202
2     200
4     199
19    194
1     192
12    192
10    190
7     188
13    188
9     184
16    183
22    181
21    180
11    178
6     176
0     176
14    169
3     167
Name: count, dtype: int64

In [55]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024,19
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024,2
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024,19
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024,22

In [57]:
df.datetime.dt.day_name()

0          Sunday
1        Saturday
2          Friday
4          Friday
6          Monday
          ...
9988     Saturday
9990     Thursday
9993    Wednesday
9996    Wednesday
9999     Saturday
Name: datetime, Length: 4611, dtype: object

In [59]:
df.day_name.value_counts()

day_name
Sunday       782
Monday       740
Tuesday      736
Saturday     608
Thursday     590
Friday       582
Wednesday    573
Name: count, dtype: int64

In [60]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024,19
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024,2
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024,19
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024,22

In [61]:
df.services.unique()

array(['bike', 'bike lite', 'parcel', 'cab economy', 'auto', 'auto share',
       'cab premium'], dtype=object)

In [62]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024,19
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024,2
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024,19
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024,22

In [67]:
cab_df = df[(df.services == "cab economy") | (df.services == "cab premium")]

In [70]:
cab_df.day_name.value_counts()

day_name
Sunday       237
Monday       216
Tuesday      203
Friday       172
Saturday     168
Thursday     158
Wednesday    153
Name: count, dtype: int64

In [72]:
df.services.value_counts()

services
auto           718
auto share     690
cab premium    657
cab economy    650
bike lite      644
parcel         635
bike           617
Name: count, dtype: int64

In [73]:
bike_df = df[(df.services == "bike lite") | (df.services == "bike")]

In [76]:
bike_df.day_name.value_counts()

day_name
Sunday       213
Monday       202
Tuesday      201
Thursday     171
Wednesday    163
Saturday     160
Friday       151
Name: count, dtype: int64

In [77]:
df.head()

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
0,bike,completed,Banashankari 7th Stage,Richmond Road,99,RD8660319589404637,18.68,93.09,2.32,95.41,Amazon Pay,2024-06-23 19:18:20,Sunday,2024,19
1,bike lite,completed,Indiranagar North,Sahakar Nagar,48,RD4484661533610497,42.55,420.77,11.68,432.45,QR scan,2024-07-06 02:42:20,Saturday,2024,2
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
4,cab economy,completed,Whitefield North,Brigade Road Eva Mall,44,RD6627722888214728,5.61,786.30,21.40,807.70,Paytm,2024-07-12 19:36:20,Friday,2024,19
6,bike lite,completed,Kadubeesanahalli,Banashankari 2nd Stage,30,RD1872668675732568,11.61,685.89,6.11,692.00,Amazon Pay,2024-07-01 22:54:20,Monday,2024,22

In [78]:
df[(df.services == "parcel")]

,services,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method,datetime,day_name,year,hour
2,parcel,completed,MG Road Mahatma Gandhi Road,Whitefield South,112,RD1526455182706880,5.85,247.90,27.45,275.35,GPay,2024-07-19 17:55:20,Friday,2024,17
23,parcel,completed,HSR Layout Sector 6 South,Banashankari 7th Stage,90,RD9840431247305400,24.43,963.21,7.47,970.68,Paytm,2024-06-26 19:01:20,Wednesday,2024,19
52,parcel,completed,Hennur,Jayanagar 6th Block East,37,RD6800012653742400,8.90,881.84,31.58,913.42,Paytm,2024-07-09 21:04:20,Tuesday,2024,21
61,parcel,completed,Banashankari 2nd Stage,Banashankari 7th Stage,64,RD2023698783515442,34.79,547.99,7.43,555.42,QR scan,2024-07-11 22:51:20,Thursday,2024,22
68,parcel,completed,Lavelle Road,HSR Layout Sector 6 South,12,RD8812147581696017,14.03,195.09,12.50,207.59,Paytm,2024-06-24 03:33:20,Monday,2024,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9897,parcel,completed,Marathahalli Main Road,HSR Layout Sector 4,53,RD5946726178366695,31.43,867.97,43.11,911.08,Cash,2024-07-13 19:07:20,Saturday,2024,19
9914,parcel,completed,Lavelle Road,HSR Layout East,91,RD1351661281516181,7.06,396.46,20.28,416.74,Amazon Pay,2024-06-25 08:09:20,Tuesday,2024,8
9938,parcel,completed,JP Nagar,HSR Layout Sector 10 South,79,RD4295963300446411,7.28,509.33,38.90,548.23,QR scan,2024-07-21 00:06:20,Sunday,2024,0
9962,parcel,completed,Malleshwaram West,Palace Guttahalli,92,RD1756512906447472,36.18,689.63,10.17,699.80,QR scan,2024-07-06 10:08:20,Saturday,2024,10
9971,parcel,completed,Koramangala 3rd Block,Indiranagar 3rd Stage,120,RD5061268879451748,1.36,207.39,29.32,236.71,phonePy,2024-07-22 21:51:20,Monday,2024,21

In [82]:
df[df.services.str.contains('parcel')].day_name.value_counts()

day_name
Sunday       112
Tuesday      103
Saturday      96
Monday        90
Wednesday     86
Friday        78
Thursday      70
Name: count, dtype: int64

In [83]:
df.services.unique()

array(['bike', 'bike lite', 'parcel', 'cab economy', 'auto', 'auto share',
       'cab premium'], dtype=object)

In [88]:
df[df.services.str.contains('bike')].distance.sum()

31547.01

In [89]:
df[df.services.str.contains('cab')].distance.sum()

33593.11

In [90]:
df[df.services.str.contains('parcel')].distance.sum()

16260.829999999998

In [91]:
df[df.services.str.contains('auto')].distance.sum()

35664.05

In [92]:
df.services.unique()

array(['bike', 'bike lite', 'parcel', 'cab economy', 'auto', 'auto share',
       'cab premium'], dtype=object)

In [96]:
df[df.services.isin(['cab economy', 'cab premium', 'auto', 'auto share'])].distance.sum()

69257.16

In [98]:
df.groupby('services')['distance'].sum()

services
auto           18413.76
auto share     17250.29
bike           15698.52
bike lite      15848.49
cab economy    16460.98
cab premium    17132.13
parcel         16260.83
Name: distance, dtype: float64