In [2]:
import pandas as pd

data = {
    "Name":["Rahul", "Alena", "Ravi", "Neha"],
    "Age" : [21,24,23,20],
    "City" : ['Delhi', 'Mumbai', 'Pune', 'Bangalore'],
    "Marks" :[90, 89, 70, 79]
}

df = pd.DataFrame(data)
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [4]:
df.head(2)

    Name  Age    City  Marks
0  Rahul   21   Delhi     90
1  Alena   24  Mumbai     89

In [6]:
df.head(3)

    Name  Age    City  Marks
0  Rahul   21   Delhi     90
1  Alena   24  Mumbai     89
2   Ravi   23    Pune     70

In [9]:
df.tail(1)

   Name  Age       City  Marks
3  Neha   20  Bangalore     79

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Marks   4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [11]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   22.000000  82.000000
std     1.825742   9.416298
min    20.000000  70.000000
25%    20.750000  76.750000
50%    22.000000  84.000000
75%    23.250000  89.250000
max    24.000000  90.000000

In [12]:
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [13]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [15]:
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [14]:
df.shape

(4, 4)

In [16]:
df

    Name  Age       City  Marks
0  Rahul   21      Delhi     90
1  Alena   24     Mumbai     89
2   Ravi   23       Pune     70
3   Neha   20  Bangalore     79

In [21]:
# df.Name
df['Name']

0    Rahul
1    Alena
2     Ravi
3     Neha
Name: Name, dtype: object

In [18]:
df.Age

0    21
1    24
2    23
3    20
Name: Age, dtype: int64

In [20]:
df.City

0        Delhi
1       Mumbai
2         Pune
3    Bangalore
Name: City, dtype: object

In [22]:
df[['Name', 'Marks']]

    Name  Marks
0  Rahul     90
1  Alena     89
2   Ravi     70
3   Neha     79