In [ ]:
!pip install plotly

In [ ]:
!pip install nbformat

#### 1. Line Chart

In [4]:
import plotly.express as px

In [8]:
df = px.data.gapminder()
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [11]:
df = px.data.gapminder().query("country=='India'")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
696,India,Asia,1952,37.373,372000000,546.565749,IND,356
697,India,Asia,1957,40.249,409000000,590.061996,IND,356
698,India,Asia,1962,43.605,454000000,658.347151,IND,356
699,India,Asia,1967,47.193,506000000,700.770611,IND,356
700,India,Asia,1972,50.651,567000000,724.032527,IND,356
701,India,Asia,1977,54.208,634000000,813.337323,IND,356
702,India,Asia,1982,56.596,708000000,855.723538,IND,356
703,India,Asia,1987,58.553,788000000,976.512676,IND,356
704,India,Asia,1992,60.223,872000000,1164.406809,IND,356
705,India,Asia,1997,61.765,959000000,1458.817442,IND,356
706,India,Asia,2002,62.879,1034172547,1746.769454,IND,356
707,India,Asia,2007,64.698,1110396331,2452.210407,IND,356

##### i. Year vs Life Expectancy

In [18]:
import plotly.express as px

px.line(df, x="year", y="lifeExp", 
        title="Life Expectancy In India",
        color_discrete_sequence=['red'],
        markers=True)

In [14]:
px.line(df, x="year", y="pop")

In [15]:
px.line(df, x="year", y="gdpPercap")

In [21]:
df = px.data.gapminder()
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [22]:
df.country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [23]:
df = px.data.gapminder().query("country in ['India','China']")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
288,China,Asia,1952,44.00000,556263527,400.448611,CHN,156
289,China,Asia,1957,50.54896,637408000,575.987001,CHN,156
290,China,Asia,1962,44.50136,665770000,487.674018,CHN,156
291,China,Asia,1967,58.38112,754550000,612.705693,CHN,156
292,China,Asia,1972,63.11888,862030000,676.900092,CHN,156
293,China,Asia,1977,63.96736,943455000,741.237470,CHN,156
294,China,Asia,1982,65.52500,1000281000,962.421381,CHN,156
295,China,Asia,1987,67.27400,1084035000,1378.904018,CHN,156
296,China,Asia,1992,68.69000,1164970000,1655.784158,CHN,156
297,China,Asia,1997,70.42600,1230075000,2289.234136,CHN,156
298,China,Asia,2002,72.02800,1280400000,3119.280896,CHN,156
299,China,Asia,2007,72.96100,1318683096,4959.114854,CHN,156
696,India,Asia,1952,37.37300,372000000,546.565749,IND,356
697,India,Asia,1957,40.24900,409000000,590.061996,IND,356
698,India,Asia,1962,43.60500,454000000,658.347151,IND,356
699,India,Asia,1967,47.19300,506000000,700.770611,IND,356
700,India,Asia,1972,50.65100,567000000,724.032527,IND,356
701,India,Asia,1977,54.20800,634000000,813.337323,IND,356
702,India,Asia,1982,56.59600,708000000,855.723538,IND,356
703,India,Asia,1987,58.55300,788000000,976.512676,IND,356
704,India,Asia,1992,60.22300,872000000,1164.406809,IND,356
705,India,Asia,1997,61.76500,959000000,1458.817442,IND,356
706,India,Asia,2002,62.87900,1034172547,1746.769454,IND,356
707,India,Asia,2007,64.69800,1110396331,2452.210407,IND,356

In [26]:
px.line(df, x='year', y='gdpPercap', color="country")

In [ ]:
df = px.data.gapminder()
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

#### 2. Bar Chart

In [27]:
import pandas as pd
data = {
    "Product":["Phone","Laptop","Tablet","TV"],
    "Sales" : [50000, 60000, 20000, 30000]
}

df = pd.DataFrame(data)
df

  Product  Sales
0   Phone  50000
1  Laptop  60000
2  Tablet  20000
3      TV  30000

In [29]:
px.bar(df, x="Product", y="Sales", color="Product")

In [ ]:
px.bar(df, x="Sales", y="Product", color="Product",
       orientation="h")

#### 3. Scatter Plot

In [33]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [35]:
px.scatter(df, x="total_bill", y="tip")

#### 4. Pie Chart

In [36]:
data = {
    "lang":['Python', 'C', 'C++', 'Java', 'Go'],
    "users" :[50, 30, 40, 45, 15]
}
df = pd.DataFrame(data)
df

     lang  users
0  Python     50
1       C     30
2     C++     40
3    Java     45
4      Go     15

In [40]:
px.pie(df, names='lang', values="users")

#### 5. Donut chart

In [43]:
px.pie(df, names='lang', values="users", 
       hole=0.4)

#### 6. Histogram

In [ ]:
df = px.data.tips()
df

In [51]:
px.histogram(df, x="total_bill", nbins=25)

#### 7. Boxplot

In [ ]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
import matplotlib.pyplot as plt
plt.boxplot(df.total_bill);

In [ ]:
import seaborn as sns
sns.boxplot(df.total_bill);

In [ ]:
import plotly.express as px
px.box(df, y="total_bill")

#### 8. Heatmap

In [ ]:
df.head()

In [64]:
corr = df.corr(numeric_only=True)
corr

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [ ]:
plt.imshow(corr);

In [ ]:
sns.heatmap(corr);

In [77]:
px.imshow(corr)